[project]
name = "gpu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.3",
    "ninja>=1.11.1.4",
    "numpy>=2.2.6",
    "scikit-learn>=1.7.1",
    "torch>=2.7.1",
]
